stages:
    - deploy

pages:
  image: registry.gitlab.com/gkalian/gitlab-allure-history-java/image:main
  stage: deploy
  script:
    - /home/groovy/bin/groovy generate_index.groovy public
    - echo "Publish to GitLab Pages"
  artifacts:
    expire_in: 7 day
    paths:
      - public
